//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverSpec.
func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HACluster) DeepCopyInto(out *HACluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HACluster.
func (in *HACluster) DeepCopy() *HACluster {
	if in == nil {
		return nil
	}
	out := new(HACluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HACluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAClusterList) DeepCopyInto(out *HAClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HACluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAClusterList.
func (in *HAClusterList) DeepCopy() *HAClusterList {
	if in == nil {
		return nil
	}
	out := new(HAClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAClusterSpec) DeepCopyInto(out *HAClusterSpec) {
	*out = *in
	in.Primary.DeepCopyInto(&out.Primary)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]ReplicaSite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Failover = in.Failover
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAClusterSpec.
func (in *HAClusterSpec) DeepCopy() *HAClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HAClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAClusterStatus) DeepCopyInto(out *HAClusterStatus) {
	*out = *in
	if in.LastFailoverTime != nil {
		in, out := &in.LastFailoverTime, &out.LastFailoverTime
		*out = (*in).DeepCopy()
	}
	if in.Sites != nil {
		in, out := &in.Sites, &out.Sites
		*out = make([]SiteStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAClusterStatus.
func (in *HAClusterStatus) DeepCopy() *HAClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HAClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresProbe) DeepCopyInto(out *PostgresProbe) {
	*out = *in
	in.UserSecretRef.DeepCopyInto(&out.UserSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresProbe.
func (in *PostgresProbe) DeepCopy() *PostgresProbe {
	if in == nil {
		return nil
	}
	out := new(PostgresProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrimarySite) DeepCopyInto(out *PrimarySite) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.PostgresProbe != nil {
		in, out := &in.PostgresProbe, &out.PostgresProbe
		*out = new(PostgresProbe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrimarySite.
func (in *PrimarySite) DeepCopy() *PrimarySite {
	if in == nil {
		return nil
	}
	out := new(PrimarySite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSite) DeepCopyInto(out *ReplicaSite) {
	*out = *in
	in.KubeconfigSecretRef.DeepCopyInto(&out.KubeconfigSecretRef)
	out.ClusterRef = in.ClusterRef
	if in.PostgresProbe != nil {
		in, out := &in.PostgresProbe, &out.PostgresProbe
		*out = new(PostgresProbe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSite.
func (in *ReplicaSite) DeepCopy() *ReplicaSite {
	if in == nil {
		return nil
	}
	out := new(ReplicaSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteStatus) DeepCopyInto(out *SiteStatus) {
	*out = *in
	if in.LastObservedTime != nil {
		in, out := &in.LastObservedTime, &out.LastObservedTime
		*out = (*in).DeepCopy()
	}
	if in.ReplicationLagMilliseconds != nil {
		in, out := &in.ReplicationLagMilliseconds, &out.ReplicationLagMilliseconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteStatus.
func (in *SiteStatus) DeepCopy() *SiteStatus {
	if in == nil {
		return nil
	}
	out := new(SiteStatus)
	in.DeepCopyInto(out)
	return out
}
